compiler.aro.aro.annex_g {
  complexFloatDiv
  complexFloatMul
}

compiler.aro.aro.Attribute.names {
  NameBuf
  Tag
  data
  exists
  findInList
  fromName
  fromTag
  longest_name
  nameFromTag
  nameFromTagIntoBuf
  nameFromUniqueIndex
  shortest_name
  span
  tagFromName
  uniqueIndex
  with
}

compiler.aro.aro.Attribute {
  Alignment
  Arguments
  ArgumentsForTag
  Formatting
  Identifier
  Iterator
  Kind
  Syntax
  Tag
  aarch64_sve_pcs
  aarch64_vector_pcs
  access
  alias
  aligned
  alloc_align
  alloc_size
  allocate
  allocator
  always_inline
  appdomain
  applyEnumeratorAttributes
  applyFieldAttributes
  applyFunctionAttributes
  applyLabelAttributes
  applyParameterAttributes
  applyStatementAttributes
  applyTypeAttributes
  applyVariableAttributes
  artificial
  asm_label
  assume_aligned
  availability
  calling_convention
  cdecl
  choices
  cleanup
  code_seg
  cold
  common
  constructor
  copy
  deprecated
  designated_init
  destructor
  diagnose
  diagnoseAlignment
  diagnoseIdent
  dllexport
  dllimport
  externally_visible
  fallthrough
  fastcall
  flatten
  format
  format_arg
  fromString
  gnu_inline
  hot
  ifunc
  initArguments
  initSlice
  initType
  internal_linkage
  interrupt
  interrupt_handler
  jitintrinsic
  leaf
  malloc
  maxArgCount
  may_alias
  mode
  ms_abi
  naked
  next
  no_address_safety_analysis
  no_icf
  no_instrument_function
  no_profile_instrument_function
  no_reorder
  no_sanitize
  no_sanitize_address
  no_sanitize_coverage
  no_sanitize_thread
  no_sanitize_undefined
  no_split_stack
  no_stack_limit
  no_stack_protector
  noclone
  nocommon
  nodiscard
  noinit
  noipa
  nonstring
  noplt
  normalize
  nothrow
  nullability
  patchable_function_entry
  pcs
  persistent
  process
  pure
  reproducible
  requiredArgCount
  restrict
  retain
  returns_nonnull
  returns_twice
  riscv_vector_cc
  safebuffers
  scalar_storage_order
  section
  selectany
  sentinel
  simd
  single
  spectre
  stack_protect
  stdcall
  symver
  sysv_abi
  target
  target_clones
  thiscall
  thread
  tls_model
  toSyntax
  transparent_union
  unaligned
  unavailable
  uninitialized
  unsafe_indexable
  unsequenced
  unused
  used
  uuid
  vector_size
  vectorcall
  visibility
  visibilityFromString
  wantsAlignment
  wantsIdentEnum
  warn_if_not_aligned
  warn_unused_result
  warning
  weak
  weakref
  zero_call_used_regs
}

compiler.aro.aro.Builtins.aarch64 {
  NameBuf
  Tag
  data
  exists
  findInList
  fromName
  fromTag
  longest_name
  nameFromTag
  nameFromTagIntoBuf
  nameFromUniqueIndex
  shortest_name
  span
  tagFromName
  uniqueIndex
  with
}

compiler.aro.aro.Builtins.amdgcn {
  NameBuf
  Tag
  data
  exists
  findInList
  fromName
  fromTag
  longest_name
  nameFromTag
  nameFromTagIntoBuf
  nameFromUniqueIndex
  shortest_name
  span
  tagFromName
  uniqueIndex
  with
}

compiler.aro.aro.Builtins.arm {
  NameBuf
  Tag
  data
  exists
  findInList
  fromName
  fromTag
  longest_name
  nameFromTag
  nameFromTagIntoBuf
  nameFromUniqueIndex
  shortest_name
  span
  tagFromName
  uniqueIndex
  with
}

compiler.aro.aro.Builtins.bpf {
  NameBuf
  Tag
  data
  exists
  findInList
  fromName
  fromTag
  longest_name
  nameFromTag
  nameFromTagIntoBuf
  nameFromUniqueIndex
  shortest_name
  span
  tagFromName
  uniqueIndex
  with
}

compiler.aro.aro.Builtins.common {
  NameBuf
  Tag
  data
  exists
  findInList
  fromName
  fromTag
  longest_name
  nameFromTag
  nameFromTagIntoBuf
  nameFromUniqueIndex
  shortest_name
  span
  tagFromName
  uniqueIndex
  with
}

compiler.aro.aro.Builtins.eval {
  eval
}

compiler.aro.aro.Builtins.hexagon {
  NameBuf
  Tag
  data
  exists
  findInList
  fromName
  fromTag
  longest_name
  nameFromTag
  nameFromTagIntoBuf
  nameFromUniqueIndex
  shortest_name
  span
  tagFromName
  uniqueIndex
  with
}

compiler.aro.aro.Builtins.loongarch {
  NameBuf
  Tag
  data
  exists
  findInList
  fromName
  fromTag
  longest_name
  nameFromTag
  nameFromTagIntoBuf
  nameFromUniqueIndex
  shortest_name
  span
  tagFromName
  uniqueIndex
  with
}

compiler.aro.aro.Builtins.mips {
  NameBuf
  Tag
  data
  exists
  findInList
  fromName
  fromTag
  longest_name
  nameFromTag
  nameFromTagIntoBuf
  nameFromUniqueIndex
  shortest_name
  span
  tagFromName
  uniqueIndex
  with
}

compiler.aro.aro.Builtins.nvptx {
  NameBuf
  Tag
  data
  exists
  findInList
  fromName
  fromTag
  longest_name
  nameFromTag
  nameFromTagIntoBuf
  nameFromUniqueIndex
  shortest_name
  span
  tagFromName
  uniqueIndex
  with
}

compiler.aro.aro.Builtins.powerpc {
  NameBuf
  Tag
  data
  exists
  findInList
  fromName
  fromTag
  longest_name
  nameFromTag
  nameFromTagIntoBuf
  nameFromUniqueIndex
  shortest_name
  span
  tagFromName
  uniqueIndex
  with
}

compiler.aro.aro.Builtins.properties {
  Attributes
  Header
  Language
  isVarArgs
}

compiler.aro.aro.Builtins.riscv {
  NameBuf
  Tag
  data
  exists
  findInList
  fromName
  fromTag
  longest_name
  nameFromTag
  nameFromTagIntoBuf
  nameFromUniqueIndex
  shortest_name
  span
  tagFromName
  uniqueIndex
  with
}

compiler.aro.aro.Builtins.s390x {
  NameBuf
  Tag
  data
  exists
  findInList
  fromName
  fromTag
  longest_name
  nameFromTag
  nameFromTagIntoBuf
  nameFromUniqueIndex
  shortest_name
  span
  tagFromName
  uniqueIndex
  with
}

compiler.aro.aro.Builtins.TypeDescription {
  Component
  ComponentIterator
  TypeIterator
  init
  next
  peek
}

compiler.aro.aro.Builtins.ve {
  NameBuf
  Tag
  data
  exists
  findInList
  fromName
  fromTag
  longest_name
  nameFromTag
  nameFromTagIntoBuf
  nameFromUniqueIndex
  shortest_name
  span
  tagFromName
  uniqueIndex
  with
}

compiler.aro.aro.Builtins.x86 {
  NameBuf
  Tag
  data
  exists
  findInList
  fromName
  fromTag
  longest_name
  nameFromTag
  nameFromTagIntoBuf
  nameFromUniqueIndex
  shortest_name
  span
  tagFromName
  uniqueIndex
  with
}

compiler.aro.aro.Builtins.x86_64 {
  NameBuf
  Tag
  data
  exists
  findInList
  fromName
  fromTag
  longest_name
  nameFromTag
  nameFromTagIntoBuf
  nameFromUniqueIndex
  shortest_name
  span
  tagFromName
  uniqueIndex
  with
}

compiler.aro.aro.Builtins.xcore {
  NameBuf
  Tag
  data
  exists
  findInList
  fromName
  fromTag
  longest_name
  nameFromTag
  nameFromTagIntoBuf
  nameFromUniqueIndex
  shortest_name
  span
  tagFromName
  uniqueIndex
  with
}

compiler.aro.aro.Builtins {
  Expanded
  FromName
  Tag
  deinit
  fromName
  getOrCreate
  lookup
}

compiler.aro.aro.char_info.identifier_tables {
  chunk
  leaf
  trie_continue
  trie_start
}

compiler.aro.aro.char_info {
  CanonicalCombiningClass
  NfcQuickCheck
  getCanonicalClass
  homoglyph
  isC11DisallowedInitialIdChar
  isC11IdChar
  isC99DisallowedInitialIDChar
  isC99IdChar
  isInvisible
  isNormalized
  isXidContinue
  isXidStart
}

compiler.aro.aro.CodeGen {
  genIr
}

compiler.aro.aro.Compilation {
  AddSourceError
  CharUnitSize
  Diagnostic
  Environment
  Error
  Include
  IncludeType
  InitOptions
  Kind
  SourceEpoch
  SystemDefinesMode
  Type
  WhichInclude
  addDefaultPragmaHandlers
  addPragmaHandler
  addSourceAlias
  addSourceFromBuffer
  addSourceFromFile
  addSourceFromOwnedBuffer
  addSourceFromPath
  backslash_newline_escape
  bit_int_max_bits
  ctrl_z_eof
  default
  deinit
  findEmbed
  findInclude
  fixedEnumTagType
  float80Type
  generateBuiltinMacros
  getCharSignedness
  getPragma
  getSource
  getSourceMTimeUncached
  hasClangStyleBoundsSafety
  hasFloat128
  hasHalfPrecisionFloatABI
  hasInclude
  init
  initSearchPath
  intLeastN
  internString
  isFramework
  isSystem
  isTargetAbi
  isTargetArch
  isTargetOs
  isTargetVariantEnvironment
  isTargetVariantOs
  isTargetVendor
  loadAll
  locSlice
  maxArrayBytes
  ms_search_rule
  nextLargestIntSameSign
  pragmaEvent
  sourceEpoch
  testing
  wcharMax
}

compiler.aro.aro.DepFile {
  Format
  addDependency
  addDependencyDupe
  deinit
  write
}

compiler.aro.aro.Diagnostics {
  Kind
  Message
  Option
  State
  add
  addWithLocation
  all
  clang
  deinit
  effectiveKind
  extra
  formatArgs
  formatInt
  formatString
  gnu
  implicit
  microsoft
  most
  set
  templateIndex
  unused
  warningExists
  write
}

compiler.aro.aro.Driver.Distro {
  HashStyle
  Tag
  detect
  getHashStyle
  isAlpine
  isDebian
  isGentoo
  isOpenSUSE
  isRedhat
  isUbuntu
}

compiler.aro.aro.Driver.GCCDetector {
  appendToolPath
  deinit
  discover
}

compiler.aro.aro.Driver.GCCVersion {
  isLessThan
  order
  parse
  toUnsigned
}

compiler.aro.aro.Driver.Multilib {
  Detected
  Filter
  exists
  filter
  flags
  init
  multilibs
  select
}

compiler.aro.aro.Driver {
  Linker
  deinit
  detectMode
  err
  errorDescription
  fatal
  getDepFileName
  getPICMode
  getPreprocessorDumpMode
  initDepFile
  invokeLinker
  main
  parseArgs
  printDiagnosticsStats
  usage
  warn
}

compiler.aro.aro.features {
  hasExtension
  hasFeature
}

compiler.aro.aro.Hideset {
  Hideset
  Index
  clearAndFree
  clearRetainingCapacity
  contains
  deinit
  get
  intersection
  prepend
  put
}

compiler.aro.aro.InitList {
  deinit
  empty
  find
}

compiler.aro.aro.LangOpts {
  BoundsSafety
  Compiler
  FPEvalMethod
  Standard
  StdCVersionMacro
  atLeast
  codepointAllowedInIdentifier
  defaultGccVersion
  hasChar8_T
  hasDigraphs
  isExplicitGNU
  isGNU
  setCharSignedness
  setEmulatedCompiler
  setFpEvalMethod
  setMSExtensions
  setStandard
}

compiler.aro.aro.Parser.Diagnostic {
  addr_of_bitfield
  addr_of_register
  addr_of_rvalue
  align_ignored
  alignas_on_func
  alignas_on_param
  alignas_unavailable
  alignof_expr
  alloc_align_required_int_param
  alloc_align_requires_ptr_return
  anonymous_struct
  argument_types_differ
  arr_init_too_long
  array_address_to_bool
  array_after
  array_argument_too_small
  array_before
  array_func_elem
  array_incomplete_elem
  array_init_str
  array_not_assignable
  array_overflow
  array_qualifiers
  array_size_non_int
  array_too_large
  atomic_address_pointer
  atomic_address_type
  atomic_array
  atomic_atomic
  atomic_auto
  atomic_complex
  atomic_func
  atomic_incomplete
  atomic_qualified
  attribute_arg_invalid
  attribute_int_out_of_range
  attribute_not_enough_args
  attribute_param_out_of_bounds
  attribute_requires_identifier
  attribute_requires_pointer
  attribute_requires_string
  attribute_todo
  attribute_too_many_args
  auto_on_global
  auto_type_array
  auto_type_extension
  auto_type_from_bitfield
  auto_type_not_allowed
  auto_type_requires_initializer
  auto_type_requires_plain_declarator
  auto_type_requires_single_declarator
  auto_type_self_initialized
  auto_type_with_init_list
  binary_integer_literal
  bit_int
  bit_int_vec_not_pow2
  bit_int_vec_too_small
  bitfield_too_big
  bitint_suffix
  break_not_in_loop_or_switch
  builtin_choose_cond
  builtin_must_be_called
  builtin_unused
  c23_auto_array
  c23_auto_not_allowed
  c23_auto_requires_initializer
  c23_auto_single_declarator
  c23_auto_with_init_list
  c99_compat
  callconv_non_func
  callconv_not_supported
  callee_with_static_array
  cannot_apply_attribute_to_statement
  cannot_combine_spec
  cannot_combine_spec_qt
  cannot_combine_with_typeof
  case_not_in_switch
  case_val_unavailable
  cast_to_incomplete_type
  cast_to_same_type
  cast_to_smaller_int
  closing_paren
  comparison_distinct_ptr
  comparison_ptr_int
  complex_component_init
  complex_conj
  complex_int
  complex_prefix_postfix_op
  cond_expr_type
  conflicting_nullability
  const_decl_folded
  const_decl_folded_vla
  const_var_assignment
  constexpr_requires_const
  continue_not_in_loop
  convertvector_arg
  convertvector_size
  declarator_name_tok
  declared_const_here
  declspec_attr_not_supported
  declspec_not_allowed_after_declarator
  declspec_not_enabled
  def_no_proto_deprecated
  deprecated_declarations
  deprecated_note
  deref_incomplete_ty_ptr
  designated_init_invalid
  designated_init_needed
  division_by_zero
  division_by_zero_macro
  dollar_in_identifier_extension
  dollars_in_identifiers
  duplicate_asm_qual
  duplicate_decl_spec
  duplicate_label
  duplicate_member
  duplicate_nullability
  duplicate_switch_case
  elementwise_type
  empty_aggregate_init_braces
  empty_case_range
  empty_char_literal_error
  empty_enum
  empty_if_body
  empty_if_body_note
  empty_initializer
  empty_record
  empty_record_size
  empty_translation_unit
  enum_atomic_ignored
  enum_different_explicit_ty
  enum_fixed
  enum_forward_declaration
  enum_invalid_underlying_type
  enum_not_representable
  enum_not_representable_fixed
  enum_prev_fixed
  enum_prev_nonfixed
  enum_qualifiers_ignored
  enum_too_large
  enum_val_unavailable
  enumerator_overflow
  enumerator_too_large
  enumerator_too_small
  error_attribute
  excess_array_init
  excess_scalar_init
  excess_str_init
  excess_struct_init
  excess_union_init
  excess_vector_init
  expected_arguments
  expected_arguments_old
  expected_at_least_arguments
  expected_eof
  expected_expr
  expected_external_decl
  expected_fn_body
  expected_ident_or_l_paren
  expected_identifier
  expected_integer_constant_expr
  expected_invalid
  expected_member_name
  expected_param_decl
  expected_parens_around_typename
  expected_record_ty
  expected_stmt
  expected_str_literal
  expected_str_literal_in
  expected_token
  expected_type
  exponent_has_no_digits
  extension_token_used
  extern_initializer
  extra_semi
  field_incomplete_ty
  flexible_in_empty
  flexible_in_empty_msvc
  flexible_in_union
  flexible_in_union_msvc
  flexible_non_final
  float_literal_in_pp_expr
  float_out_of_range
  float_overflow_conversion
  float_to_int
  float_value_changed
  float_zero_conversion
  forward_declaration_here
  func_cannot_return_array
  func_cannot_return_func
  func_does_not_return
  func_field
  func_init
  func_not_in_root
  func_should_return
  func_spec_non_func
  generic_array_type
  generic_duplicate
  generic_duplicate_default
  generic_duplicate_here
  generic_func_type
  generic_no_match
  generic_qual_type
  gnu_asm_disabled
  gnu_imaginary_constant
  gnu_label_as_value
  gnu_missing_eq_designator
  gnu_pointer_arith
  gnu_statement_expression
  gnu_switch_range
  gnu_union_cast
  hex_floating_constant_requires_exponent
  ident_or_l_brace
  identifier_not_normalized
  ignore_always_inline
  ignore_cold
  ignore_common
  ignore_hot
  ignore_nocommon
  ignore_noinline
  ignored_attribute
  ignored_record_attr
  illegal_initializer
  illegal_storage_on_func
  implicit_builtin
  implicit_builtin_header_note
  implicit_func_decl
  implicit_int_to_ptr
  implicit_ptr_to_int
  implicitly_unsigned_literal
  incompatible_arg
  incompatible_array_init
  incompatible_assign
  incompatible_init
  incompatible_pointers
  incompatible_ptr_arg
  incompatible_ptr_arg_sign
  incompatible_ptr_assign
  incompatible_ptr_assign_sign
  incompatible_ptr_init
  incompatible_ptr_init_sign
  incompatible_return
  incompatible_return_sign
  incompatible_va_arg
  incompatible_vec_types
  indirection_ptr
  initializer_overrides
  int_literal_too_big
  int_value_changed
  invalid_alignof
  invalid_argument_un
  invalid_array_designator
  invalid_asm_output
  invalid_asm_str
  invalid_attribute_location
  invalid_bin_types
  invalid_binary_digit
  invalid_cast_operand_type
  invalid_cast_to_float
  invalid_cast_to_pointer
  invalid_cast_type
  invalid_compound_literal_storage_class
  invalid_computed_goto
  invalid_fallthrough
  invalid_field_designator
  invalid_float_suffix
  invalid_identifier_start_char
  invalid_imag
  invalid_index
  invalid_int_suffix
  invalid_noreturn
  invalid_nullability
  invalid_object_cast
  invalid_octal_digit
  invalid_old_style_params
  invalid_preproc_operator
  invalid_real
  invalid_sizeof
  invalid_static_star
  invalid_storage_on_param
  invalid_subscript
  invalid_union_cast
  invalid_utf8
  invalid_vec_conversion
  invalid_vec_conversion_int
  invalid_vec_conversion_scalar
  invalid_vec_elem_ty
  invalid_void_param
  label_compound_end
  local_variable_attribute
  main_return_type
  maximum_alignment
  meaningless_asm_qual
  member_expr_atomic
  member_expr_not_ptr
  member_expr_ptr
  minimum_alignment
  missing_declaration
  missing_semicolon
  missing_type_specifier
  missing_type_specifier_c23
  mixing_decimal_floats
  multiple_bounds_annotations
  multiple_default
  multiple_storage_class
  must_use_enum
  must_use_struct
  must_use_union
  negative_alignment
  negative_array_designator
  negative_array_size
  negative_bitwidth
  negative_shift_count
  no_such_field_designator
  no_such_member
  nodiscard_unused
  non_int_bitfield
  non_null_argument
  non_object_not_assignable
  non_pow2_align
  non_string_ignored
  nontemporal_address_pointer
  nontemporal_address_type
  not_assignable
  not_callable
  not_floating_type
  nullability_extension
  offsetof_array
  offsetof_incomplete
  offsetof_ty
  old_style_flexible_struct
  omitting_parameter_name
  oob_array_designator
  out_of_scope_use
  overflow
  overflow_builtin_requires_int
  overflow_result_requires_ptr
  packed_member_address
  param_before_var_args
  param_not_declared
  parameter_here
  parameter_incomplete_ty
  parameter_missing
  passing_args_to_kr
  plain_complex
  pointer_arith_single
  pointer_arith_void
  pointer_bounds_declared_here
  pointer_mismatch
  pre_c23_compat
  predefined_top_level
  previous_case
  previous_declaration
  previous_definition
  previous_initializer
  previous_label
  ptr_arg_discards_quals
  ptr_arithmetic_incomplete
  ptr_assign_discards_quals
  ptr_init_discards_quals
  ptr_ret_discards_quals
  qual_cast
  qual_on_ret_type
  qualifier_non_outermost_array
  record_too_large
  redefinition
  redefinition_different_sym
  redefinition_incompatible
  redefinition_of_parameter
  redefinition_of_typedef
  redundant_bounds_annotation
  register_on_global
  register_on_global_compound_literal
  restrict_non_pointer
  shufflevector_arg
  shufflevector_index_too_big
  shufflevector_negative_index
  shufflevector_same_type
  sign_conversion
  signed_bit_int_too_big
  signed_bit_int_too_small
  single_requires_zero_index
  sizeof_array_arg
  sizeof_returns_zero
  star_non_param
  statement_int
  statement_scalar
  static_assert_failure
  static_assert_failure_message
  static_assert_missing_message
  static_assert_not_constant
  static_func_not_global
  static_non_outermost_array
  static_non_param
  stmt_expr_not_allowed_file_scope
  str_init_too_long
  string_literal_to_bool
  subtract_pointers_zero_elem_size
  suggest_pointer_for_invalid_fp16
  tentative_array
  tentative_definition_incomplete
  threadlocal_non_var
  to_match_brace
  to_match_bracket
  to_match_paren
  todo
  too_big_shift_count
  too_many_scalar_init_braces
  transparent_union_one_field
  transparent_union_size
  transparent_union_size_note
  transparent_union_wrong_type
  type_not_supported_on_target
  u8_char_lit
  unavailable
  unavailable_note
  unbound_vla
  undeclared_identifier
  undeclared_label
  unexpected_character
  unexpected_type_name
  unicode_homoglyph
  unicode_zero_width
  unknown_attr_enum
  unknown_attribute
  unknown_builtin
  unknown_type_name
  unreachable_code
  unsigned_bit_int_too_big
  unsigned_bit_int_too_small
  unsupported_str_cat
  unterminated_char_literal_error
  unused_value
  useless_static
  va_func_fixed_args
  va_func_not_always_inline
  va_func_not_in_func
  va_pack_non_call
  va_pack_non_final_arg
  va_pack_non_variadic_arg
  va_pack_non_variadic_call
  va_start_not_last_param
  variable_incomplete_ty
  variable_len_array_file_scope
  vec_size_not_multiple
  vla
  vla_field
  vla_init
  void_func_returns_value
  void_must_be_first_param
  void_only_param
  void_param_qualified
  warn_unused_result
  warning_attribute
  wrong_tag
  zero_length_array
  zero_width_named_field
}

compiler.aro.aro.Parser {
  DeclSpec
  Diagnostic
  Error
  Result
  err
  errValueChanged
  format
  getDecayedStringLiteral
  isAddressOfStringLiteral
  macroExpr
  parse
  parseNumberToken
  removeNull
  setTentativeDeclDefinition
  todo
  tokSlice
}

compiler.aro.aro.Pragma {
  Diagnostic
  Error
  do_nothing
  err
  malformed_warning_check
  parserCB
  pasteTokens
  poisoned_identifier
  pragma_error_message
  pragma_message
  pragma_pack_empty_stack
  pragma_pack_int
  pragma_pack_int_ident
  pragma_pack_lparen
  pragma_pack_rparen
  pragma_pack_show
  pragma_pack_undefined_pop
  pragma_pack_unknown_action
  pragma_poison_identifier
  pragma_poison_macro
  pragma_requires_string_literal
  pragma_warning_message
  preprocessorCB
  shouldExpandTokenAtIndex
  shouldPreserveTokens
  unknown_gcc_pragma
  unknown_gcc_pragma_directive
}

compiler.aro.aro.pragmas.gcc {
  init
}

compiler.aro.aro.pragmas.message {
  init
}

compiler.aro.aro.pragmas.once {
  init
}

compiler.aro.aro.pragmas.pack {
  init
}

compiler.aro.aro.Preprocessor.Diagnostic {
  base_file_is_clang_extension
  builtin_macro_redefined
  builtin_missing_r_paren
  cannot_convert_to_identifier
  closing_paren
  comma_deletion_va_args
  date_time
  defined_as_macro_name
  duplicate_embed_param
  elif_after_else
  elif_without_if
  elifdef_after_else
  elifdef_without_if
  elifndef_after_else
  elifndef_without_if
  else_after_else
  else_without_if
  empty_char_literal_warning
  empty_filename
  endif_without_if
  error_directive
  expansion_to_defined_func
  expansion_to_defined_obj
  expected_arguments
  expected_at_least_arguments
  expected_comma_param_list
  expected_filename
  expected_identifier
  expected_str_literal_in
  expected_value_in_expr
  extra_tokens_directive_end
  feature_check_requires_identifier
  file_name_is_clang_extension
  fn_macro_undefined
  gnu_va_macro
  hash_hash_at_end
  hash_hash_at_start
  hash_not_followed_param
  header_str_closing
  header_str_match
  include_level_is_clang_extension
  include_next
  include_next_outside_header
  incomplete_ucn
  invalid_pp_stringify_escape
  invalid_preproc_expr_start
  invalid_preproc_operator
  invalid_preprocessing_directive
  invalid_source_epoch
  invalid_token_param_list
  keyword_macro
  line_invalid_filename
  line_invalid_flag
  line_invalid_number
  line_simple_digit
  macro_name_missing
  macro_name_must_be_identifier
  macro_redefined
  malformed_embed_limit
  malformed_embed_param
  malformed_warning_check
  missing_lparen_after_builtin
  missing_paren_param_list
  newline_eof
  no_argument_variadic_macro
  pasting_formed_invalid
  poisoned_identifier
  pragma_once_in_main_file
  pragma_operator_string_literal
  previous_definition
  string_literal_in_pp_expr
  to_match_paren
  too_many_includes
  undefined_macro
  unknown_pragma
  unsupported_embed_param
  unterminated_char_literal_warning
  unterminated_comment
  unterminated_conditional_directive
  unterminated_macro_arg_list
  unterminated_macro_param_list
  unterminated_string_literal_warning
  va_opt_lparen
  va_opt_rparen
  warning_directive
  whitespace_after_macro_name
}

compiler.aro.aro.Preprocessor {
  Diagnostic
  DumpMode
  InitOptions
  Linemarkers
  Macro
  addBuiltinMacros
  addIncludeResume
  addIncludeStart
  addToken
  addTokenAssumeCapacity
  clearBuffers
  deinit
  ensureTotalTokenCapacity
  ensureUnusedTokenCapacity
  expandedSlice
  expansionSlice
  format
  init
  isBuiltin
  parse
  preprocess
  preprocessSources
  prettyPrintTokens
  testing
  tokSlice
  tokenize
}

compiler.aro.aro.record_layout {
  Error
  compute
  msvcPragmaPack
}

compiler.aro.aro.Source {
  ExpandedLocation
  Id
  Kind
  Location
  eql
  expand
  generated
  lineCol
  unused
}

compiler.aro.aro.StringInterner {
  StringId
  deinit
  intern
  lookup
  lookupExtra
}

compiler.aro.aro.SymbolStack {
  Kind
  Symbol
  declareSymbol
  define
  defineEnumeration
  defineParam
  defineSymbol
  defineTag
  defineTypedef
  deinit
  findSymbol
  findTag
  findTypedef
  get
  getPtr
  popScope
  pushScope
}

compiler.aro.aro.Target {
  ArchSubArch
  DefaultPIStatus
  FPSemantics
  SubArch
  Vendor
  cCharSignedness
  cTypeAlignment
  cTypeBitSize
  chooseValue
  default
  defaultAlignment
  defaultFpEvalMethod
  defaultFunctionAlignment
  float80Type
  forType
  get32BitArchVariant
  get64BitArchVariant
  halfPrecisionType
  hasFloat128
  hasHalfPrecisionFloatABI
  hasInt128
  ignoreNonZeroSizedBitfieldTypeAlignment
  ignoreZeroSizedBitfieldTypeAlignment
  int16Type
  int64Type
  intMaxType
  intPtrType
  isAbi
  isKnownWindowsMSVCEnvironment
  isLP64
  isMinGW
  isOs
  isPICDefaultForced
  isPICdefault
  isPIEDefault
  isPS
  isTlsSupported
  isWindowsMSVCEnvironment
  ldEmulationOption
  minFunctionAlignment
  minZeroWidthBitfieldAlignment
  nullRepr
  packAllEnums
  parse
  parseAbi
  parseAbiName
  parseArchName
  parseOs
  parseOsName
  parseVendorName
  ppcElfVersion
  ptrBitWidth
  sigAtomicType
  standardDynamicLinkerPath
  systemCompiler
  toFeature
  toLLVMTriple
  unnamedFieldAffectsAlignment
}

compiler.aro.aro.text_literal {
  Ascii
  Item
  Kind
  Parser
  c89_ucn_in_literal
  charLiteralType
  charUnitSize
  char_lit_too_wide
  char_too_large
  classify
  concat
  contentSlice
  elementType
  err
  escape_sequence_overflow
  format
  four_char_char_literal
  illegal_char_encoding_error
  illegal_char_encoding_warning
  incomplete_universal_character
  init
  internalStorageAlignment
  invalid_multichar_literal
  invalid_universal_character
  maxCodepoint
  maxInt
  missing_hex_escape
  multichar_literal_warning
  next
  ucn_basic_char_error
  ucn_basic_char_warning
  ucn_control_char_error
  ucn_control_char_warning
  unknown_escape_sequence
  warn
}

compiler.aro.aro.Tokenizer {
  Id
  Token
  allowsDigraphs
  canOpenGCCAsmStmt
  colonColon
  getTokenId
  isMacroIdentifier
  isStringLiteral
  lexeme
  next
  nextNoWS
  nextNoWSComments
  shouldTrackHideset
  simplifyMacroKeyword
  simplifyMacroKeywordExtra
  symbol
  validPreprocessorExprStart
}

compiler.aro.aro.Toolchain {
  FileKind
  LibGCCKind
  PathList
  RuntimeLibKind
  UnwindLibKind
  addBuiltinIncludeDir
  addFilePathLibArgs
  addPathFromComponents
  addPathIfExists
  addRuntimeLibs
  addSystemIncludeDir
  canExecute
  defineSystemIncludes
  deinit
  discover
  exists
  findProgramByName
  getAssemblerPath
  getCompilerRt
  getFilePath
  getLinkerPath
  getRuntimeLibKind
  getSysroot
  getTarget
  joinedExists
  readFile
}

compiler.aro.aro.tracy {
  Ctx
  Frame
  TracyAllocator
  allocator
  enable
  enable_allocation
  enable_callstack
  end
  init
  tracyAllocator
}

compiler.aro.aro.Tree.number_affixes {
  Prefix
  Suffix
  digitAllowed
  fromString
  isBitInt
  isFloat80
  isImaginary
  isSignedInteger
  signedness
  stringLen
}

compiler.aro.aro.Tree {
  AddrOfLabel
  ArrayAccess
  ArrayFiller
  AsmStmt
  Association
  Binary
  BreakStmt
  BuiltinCall
  BuiltinRef
  Call
  CaseStmt
  Cast
  CharLiteral
  CompoundLiteral
  CompoundStmt
  ComputedGotoStmt
  Conditional
  ContainerDecl
  ContainerForwardDecl
  ContainerInit
  ContinueStmt
  Convertvector
  DeclAttr
  DeclRef
  Default
  DefaultInit
  DefaultStmt
  DoWhileStmt
  EmptyDecl
  EnumField
  ForStmt
  Function
  GNUAssemblyQualifiers
  Generic
  GlobalAsm
  GotoStmt
  Id
  IfStmt
  Index
  Kind
  LabeledStmt
  List
  Literal
  MemberAccess
  Node
  NullStmt
  NumberPrefix
  NumberSuffix
  Operand
  OptIndex
  Param
  RecordField
  Repr
  ReturnStmt
  Shufflevector
  StaticAssert
  SwitchStmt
  Tag
  Token
  TokenIndex
  TokenWithExpansionLocs
  TypeInfo
  Typedef
  TypesCompatible
  Unary
  UnionInit
  VaArgPack
  ValueMap
  Variable
  WhileStmt
  addExpansionLocation
  addNode
  bitfieldWidth
  callableResultUsage
  checkMsEof
  deinit
  dump
  dupe
  expansionSlice
  free
  genIr
  get
  isBitFieldWidth
  isBitfield
  isImplicit
  isLval
  isLvalExtra
  loc
  pack
  packOpt
  qt
  qtOrNull
  setNode
  tok
  tokSlice
  unpack
}

compiler.aro.aro.TypeStore {
  Array
  Attributed
  BitInt
  Bounds
  Builder
  Enum
  Field
  Float
  Func
  Int
  Layout
  Param
  Pointer
  QualType
  Record
  ScalarKind
  Specifier
  Tag
  Type
  TypeDef
  TypeOf
  TypeSizeOrder
  Vector
  alignable
  alignof
  annotationAlignment
  arrayLen
  attributes
  auto_type
  base
  bf16
  bitSizeof
  bitSizeofOrNull
  bits
  c23_auto
  char
  char_pointer
  childType
  combine
  combineAtomic
  combineFromTypeof
  combineTypedef
  decay
  decimal_float_rank
  deinit
  dfloat128
  dfloat32
  dfloat64
  dfloat64x
  double
  dump
  enumIsPacked
  eql
  eqlQualified
  finish
  finishQuals
  float
  float128
  float128x
  float16
  float32
  float32x
  float64
  float64x
  floatRank
  formatModifier
  fp16
  fromTag
  fromType
  get
  getAttribute
  getRecord
  hasAttribute
  hasField
  hasIncompleteSize
  initNamedTypes
  int
  int128
  intRank
  intRankOrder
  intValueSuffix
  int_pointer
  invalid
  is
  isAnonymous
  isArithmetic
  isAutoType
  isC23Auto
  isCallable
  isFloat
  isInt
  isInvalid
  isPointer
  isQualified
  isReal
  isRealInt
  linkage
  long
  long_double
  long_long
  makeIntUnsigned
  nullptr_t
  print
  printDesugared
  printNamed
  promoteBitfield
  promoteInt
  put
  putExtra
  requestedAlignment
  sameRankDifferentSign
  scalarKind
  schar
  set
  short
  shouldDesugar
  signedness
  sizeCompare
  sizeof
  sizeofOrNull
  std
  str
  toComplex
  toReal
  uchar
  uint
  uint128
  ulong
  ulong_long
  unpack
  unqualified
  ushort
  void_pointer
  withQualifiers
}

compiler.aro.aro.Value {
  FloatToIntChangeKind
  IntCastChangeKind
  add
  bitAnd
  bitNot
  bitOr
  bitXor
  boolCast
  compare
  comparePointers
  complexConj
  decrement
  div
  floatCast
  floatToInt
  fromBool
  fromRef
  imag
  imaginaryPart
  int
  intCast
  intToFloat
  intern
  is
  isArithmetic
  isInf
  isInfSign
  isNan
  isPointer
  isZero
  maxInt
  minInt
  minSignedBits
  minUnsignedBits
  mul
  negate
  one
  pointer
  print
  printPointer
  printString
  realPart
  ref
  rem
  shl
  shr
  sub
  toBool
  toBytes
  toFloat
  toInt
  zero
}

compiler.aro.aro {
  Assembly
  CallingConvention
  CodeGen
  Compilation
  Diagnostics
  Driver
  Interner
  Ir
  Object
  Parser
  Preprocessor
  QualType
  Source
  StringInterner
  Target
  Tokenizer
  Toolchain
  Tree
  Type
  TypeStore
  Value
  version
  version_str
}

compiler.aro.assembly_backend.x86_64 {
  genAsm
  todo
}

compiler.aro.assembly_backend {
  genAsm
  x86_64
}

compiler.aro.backend.Assembly {
  deinit
  writeToFile
}

compiler.aro.backend.CodeGenOptions {
  DebugFormat
  DwarfVersion
  OptimizationLevel
  PicLevel
  default
  fromString
  hasAnyOptimizations
  isSizeOptimized
}

compiler.aro.backend.Interner {
  Array
  BigIntSpace
  Bytes
  CF128
  CF16
  CF32
  CF64
  CF80
  Complex
  F128
  F64
  F80
  Float
  Int
  Key
  OptRef
  PackedU64
  Pointer
  Record
  Ref
  Tag
  Vector
  deinit
  eql
  get
  getLen
  hash
  init
  put
  toBigInt
}

compiler.aro.backend.Ir.x86.Renderer {
  render
}

compiler.aro.backend.Ir {
  Branch
  Builder
  Call
  Data
  Decl
  DumpError
  Error
  ErrorList
  Input
  Inst
  Phi
  Ref
  Renderer
  Switch
  Tag
  addAlloc
  addArg
  addBranch
  addConstant
  addInst
  addJump
  addPhi
  addSelect
  addStore
  addSwitch
  args
  deinit
  dump
  fail
  finish
  finishFn
  inputs
  makeLabel
  render
  startBlock
  startFn
}

compiler.aro.backend.Object.Elf {
  addRelocation
  create
  declareSymbol
  deinit
  finish
  getSection
}

compiler.aro.backend.Object {
  Section
  SymbolType
  addRelocation
  create
  declareSymbol
  deinit
  finish
  getSection
}

compiler.aro.backend {
  Assembly
  CallingConvention
  CodeGenOptions
  Interner
  Ir
  Object
  version
  version_str
}

compiler.aro.main {
  main
}

compiler.build_runner {
  dependencies
  main
  printErrorMessages
  root
  std_options
}

compiler.libc {
  main
}

compiler.objcopy {
  EmitRawElfOptions
  deinit
  main
  parse
  writeSegment
}

compiler.objdump {
  main
}

compiler.reduce.Walk {
  Error
  InlineImportedFile
  Transformation
  findTransformations
}

compiler.reduce {
  main
}

compiler.resinator.ani {
  isAnimatedIcon
}

compiler.resinator.ast {
  Accelerator
  Accelerators
  BinaryExpression
  Block
  BlockValue
  BlockValueValue
  CodePageLookup
  ControlStatement
  Dialog
  FontStatement
  GroupedExpression
  Id
  Invalid
  LanguageStatement
  Literal
  Menu
  MenuItem
  MenuItemEx
  MenuItemSeparator
  Node
  NotExpression
  Popup
  PopupEx
  ResourceExternal
  ResourceRawData
  Root
  SimpleStatement
  StringTable
  StringTableString
  Toolbar
  Tree
  Type
  VersionInfo
  VersionStatement
  cast
  deinit
  dump
  getFirstToken
  getForLineNum
  getForToken
  getLastToken
  init
  isNumberExpression
  isStringLiteral
  isUserDefined
  root
  setForLineNum
  setForToken
}

compiler.resinator.bmp {
  BITMAPCOREHEADER
  BITMAPINFOHEADER
  BitmapInfo
  Compression
  ReadError
  file_header_len
  getActualPaletteByteLen
  getBitmasksByteLen
  getByteLenBetweenHeadersAndPixels
  getExpectedByteLen
  getExpectedByteLenBeforePixelData
  getExpectedPaletteByteLen
  getMissingPaletteByteLen
  getPixelDataLen
  numColorsInTable
  read
  windows_format_id
}

compiler.resinator.cli {
  Arg
  ArgSpan
  AutoIncludes
  Context
  DepfileFormat
  Diagnostics
  ErrorDetails
  InputFormat
  IoSource
  Options
  OutputFormat
  ParseError
  Preprocess
  SymbolAction
  SymbolValue
  Type
  Value
  append
  argSpan
  define
  deinit
  dumpVerbose
  extension
  filepathWithExtension
  fromString
  hasError
  index
  init
  isSupportedInputExtension
  isSupportedTransformation
  isValidIdentifier
  looksLikeFilepath
  max_string_literal_length_100_percent
  maybeAppendRC
  missingSpan
  name
  optionAndAfterSpan
  optionSpan
  optionWithoutPrefix
  parse
  parsePercent
  prefixSlice
  renderErrorMessage
  renderToStderr
  renderToTerminal
  renderToWriter
  undefine
  usage_string_after_command_name
  value
  writeUsage
}

compiler.resinator.code_pages {
  CodePage
  Codepoint
  SupportedCodePage
  UnsupportedCodePage
  Utf8
  WellFormedDecoder
  codepointAt
  decode
  getByIdentifier
  getByIdentifierEnsureSupported
  invalid
  isSupported
  sequenceLength
}

compiler.resinator.comments {
  removeComments
  removeCommentsAlloc
}

compiler.resinator.compile {
  Block
  CompileOptions
  Compiler
  Data
  DataType
  Dependencies
  FlagsExpressionContext
  Font
  FontDir
  InitError
  OpenSearchPathError
  ResourceHeader
  ResourceHeaderOptions
  SearchDir
  SizeInfo
  State
  StringTable
  StringTablesByLanguage
  add
  applyAttributes
  applyMemoryFlags
  applyNotMask
  applyOptionalStatements
  calcSize
  compile
  deinit
  dump
  evaluateAcceleratorKeyExpression
  evaluateDataExpression
  evaluateFilenameExpression
  evaluateFlagsExpression
  evaluateFlagsExpressionWithDefault
  evaluateNumberExpression
  evaluateOperator
  get
  getLanguageFromOptionalStatements
  init
  languageFromLanguageStatement
  numPaddingBytesNeeded
  parseDlgIncludeString
  parseQuotedStringAsWideString
  predefinedResourceType
  resourceHeader
  set
  sourceBytesForToken
  write
  writeAccelerators
  writeAcceleratorsData
  writeAssertNoOverflow
  writeDataPadding
  writeDialog
  writeDialogFont
  writeEmptyResource
  writeLanguageStatement
  writeMenu
  writeMenuData
  writeMenuItem
  writeNode
  writeResData
  writeResourceData
  writeResourceDataNoPadding
  writeResourceExternal
  writeResourceHeader
  writeResourceRawData
  writeRoot
  writeSizeInfo
  writeStringTable
  writeToolbar
  writeTopLevelSimpleStatement
  writeVersionInfo
  writeVersionNode
}

compiler.resinator.cvtres {
  Arch
  CoffOptions
  Diagnostics
  ParseResOptions
  ParsedResources
  Resource
  ResourceAndSize
  ResourceDataEntry
  ResourceDirectoryEntry
  ResourceDirectoryTable
  add
  dataLengths
  deinit
  description
  eql
  fromStringIgnoreCase
  hash
  init
  is32BitPreface
  isDlgInclude
  isSupported
  lessThan
  longest_name
  ordered_for_display
  parseNameOrOrdinal
  parseRes
  parseResInto
  parseResource
  put
  rvaRelocationTypeIndicator
  sort
  supported_targets
  toCoffMachineType
  totalByteLength
  writeCoff
}

compiler.resinator.disjoint_code_page {
  hasDisjointCodePage
}

compiler.resinator.errors {
  AcceleratorError
  AcceleratorErrorEnum
  BitmapReadError
  BitmapReadErrorEnum
  BitmapUnsupportedDIB
  Diagnostics
  DiagnosticsContext
  Error
  ErrorDetails
  ErrorDetailsWithoutCodePage
  ExpectedTypes
  Extra
  FileOpenError
  FileOpenErrorEnum
  FilenameStringIndex
  IconDirContext
  IconReadError
  IconReadErrorEnum
  Padding
  StatementWithU16Param
  StringAndLanguage
  Type
  VisualTokenInfo
  append
  contains
  containsAny
  deinit
  enumFromError
  init
  next
  putString
  render
  renderErrorMessage
  renderToStderr
  strings
  visualTokenInfo
  writeCommaSeparated
}

compiler.resinator.ico {
  BitmapHeader
  Entry
  IconDir
  ImageFormat
  ImageType
  ReadError
  Version
  deinit
  detect
  get
  getResDataSize
  len
  nameForErrorDisplay
  read
  res_byte_len
  res_header_byte_len
  validate
  version
  writeResData
}

compiler.resinator.lang {
  LANG_ENGLISH
  LOCALE_CUSTOM_UNSPECIFIED
  LanguageId
  MAKELANGID
  Parsed
  SUBLANG_ENGLISH_US
  isSuffixValidSortOrder
  parse
  parseInt
  tagToId
  tagToInt
}

compiler.resinator.lex {
  Error
  Id
  LexError
  LexMethod
  Lexer
  LexerOptions
  LineHandler
  Token
  calculateColumn
  currentIndexFormsLineEndingPair
  default_max_string_literal_codepoints
  dump
  firstToken
  getErrorDetails
  getLineForErrorDisplay
  getLineStartForColumnCalc
  getLineStartForErrorDisplay
  incrementLineNumber
  init
  isStringLiteral
  maybeIncrementLineNumber
  nameForErrorDisplay
  next
  nextNormal
  nextNormalWithContext
  nextWhitespaceDelimeterOnly
  parsePragmaCodePage
  slice
}

compiler.resinator.literals {
  IterativeStringParser
  Number
  ParsedCodepoint
  SourceBytes
  StringParseOptions
  StringType
  asWord
  columnWidth
  columnsUntilTabStop
  evaluateOperator
  init
  isValidNumberDataLiteral
  next
  nextUnchecked
  parseNumberLiteral
  parseQuotedAsciiString
  parseQuotedString
  parseQuotedStringAsWideString
  parseQuotedWideString
}

compiler.resinator.main {
  Data
  Error
  IoDirection
  Source
  Writer
  cleanupAfterError
  deinit
  emitAroDiagnostics
  emitCliDiagnostics
  emitDiagnostics
  emitMessage
  fromIoSource
  get
  interface
  main
  readAll
  writer
}

compiler.resinator.parse {
  AllowedTypes
  Error
  NestingContext
  OptionalParamParser
  Options
  ParseExpressionOptions
  Parser
  State
  init
  max_nested_expression_level
  max_nested_menu_level
  max_nested_version_level
  parse
  toErrorDetails
}

compiler.resinator.preprocess {
  appendAroArgs
  preprocess
}

compiler.resinator.rc {
  AcceleratorTypeAndOptions
  CommonResourceAttributes
  Control
  ControlClass
  MenuItem
  Option
  OptionalStatements
  ResourceType
  ToolbarButton
  TopLevelKeywords
  VersionBlock
  VersionInfo
  canUseRawData
  dialog_map
  eqlIgnoreCaseW
  fromRT
  fromString
  fromWideString
  hasTextParam
  isSeparator
  map
  nameForErrorDisplay
}

compiler.resinator.res {
  ALT
  ASCII
  AUTO3STATE
  AUTOCHECKBOX
  AUTORADIOBUTTON
  AcceleratorModifiers
  BORDER
  BS
  CAPTION
  CENTER
  CHECKBOX
  CHECKED
  CHILD
  CHILDWINDOW
  CLIPCHILDREN
  CLIPSIBLINGS
  CONTROL
  ControlClass
  DEFPUSHBUTTON
  DISABLED
  DISCARDABLE
  DLGFRAME
  DS
  END
  FixedFileInfo
  ForcedOrdinal
  GRAYED
  GROUP
  GROUPBOX
  HELP
  HSCROLL
  ICON
  ICONIC
  LBS
  LEFT
  LEFTTEXT
  Language
  MAXIMIZE
  MAXIMIZEBOX
  MENUBARBREAK
  MENUBREAK
  MF
  MINIMIZE
  MINIMIZEBOX
  MOVEABLE
  MemoryFlags
  MenuItemFlags
  NOINVERT
  NOTIFY
  NameOrOrdinal
  OVERLAPPED
  OVERLAPPEDWINDOW
  OWNERDRAW
  POPUP
  POPUPWINDOW
  PRELOAD
  PURE
  PUSHBOX
  PUSHBUTTON
  ParseAcceleratorKeyStringError
  RADIOBUTTON
  RIGHT
  RT
  SETFONT
  SHARED
  SHIFT
  SIZEBOX
  SS
  SYSMENU
  TABSTOP
  THICKFRAME
  TILED
  TILEDWINDOW
  TYPEMASK
  USERBUTTON
  VIRTKEY
  VISIBLE
  VSCROLL
  Version
  VersionNode
  WS
  apply
  asInt
  byteLen
  byte_len
  default
  defaults
  deinit
  fmtResourceType
  format
  fromBytes
  fromControl
  fromInt
  fromResource
  fromString
  fromUtf16Le
  getImpliedStyle
  isSet
  key
  last_accelerator_in_table
  leastSignificantCombinedParts
  markLast
  maybeNonAsciiOrdinalFromString
  maybeOrdinalFromString
  mostSignificantCombinedParts
  nameFromString
  parseAcceleratorKeyString
  predefinedResourceType
  set
  setGroup
  signature
  translate
  type_binary
  type_string
  version
  write
  writeEmpty
}

compiler.resinator.source_mapping {
  CorrespondingSpan
  ParseAndRemoveLineCommandsOptions
  ParseLineCommandsResult
  Source
  SourceMappings
  StringTable
  collapse
  deinit
  formsLineEndingPair
  get
  getCorrespondingSpan
  getOffset
  handleLineCommand
  handleLineEnd
  isRootFile
  parseAndRemoveLineCommands
  parseAndRemoveLineCommandsAlloc
  put
  set
}

compiler.resinator.utils {
  ErrorMessageType
  UncheckedSliceWriter
  getWritten
  isLineEndingPair
  isNonAsciiDigit
  renderErrorMessage
  renderErrorMessageToStderr
  write
  writeSlice
}

compiler.resinator.windows1252 {
  bestFitFromCodepoint
  toCodepoint
}

compiler.std-docs {
  main
}

compiler.test_runner {
  fuzz
  log
  main
  mainSimple
  std_options
}

compiler.translate-c.ast {
  ArgRedecl
  Array
  ArrayFiller
  ArrayTypeInfo
  BinOp
  Block
  BreakVal
  Call
  CallingConvention
  Container
  ContainerInit
  ContainerInitDot
  Data
  Discard
  EnumConstant
  Extern
  FailDecl
  Field
  FieldAccess
  Func
  HelperCall
  HelperRef
  If
  Initializer
  Node
  Param
  Payload
  Pointer
  PubInlineFn
  RootRef
  Shuffle
  SimpleVarDecl
  StringSlice
  Switch
  Tag
  TupleInit
  Type
  UnOp
  Value
  VarDecl
  While
  castTag
  create
  init
  initPayload
  isBoolRes
  isNoreturn
  last_no_payload_tag
  no_payload_count
  render
  tag
}

compiler.translate-c.builtins {
  Builtin
  map
}

compiler.translate-c.MacroTranslator {
  ParseError
  transFnMacro
  transMacro
}

compiler.translate-c.main {
  main
  usage
}

compiler.translate-c.PatternList {
  MacroProcessingError
  MacroSlicer
  deinit
  init
  match
}

compiler.translate-c.Scope {
  AliasList
  Block
  Condition
  ContainerMemberFns
  ContainerMemberFnsHashMap
  Id
  Root
  SymbolTable
  addMemberFunction
  appendNode
  complete
  contains
  containsNow
  createMangledName
  deinit
  discardVariable
  eql
  extern_local_prefix
  findBlockReturnType
  findBlockScope
  getAlias
  hash
  init
  makeMangledName
  processContainerMemberFns
  reserveMangledName
  skipVariableDiscard
  static_local_prefix
}

compiler.translate-c.Translator {
  Context
  Error
  Key
  MacroProcessingError
  Options
  QualTypeHashContext
  StrictFlexArraysLevel
  TransError
  TypeError
  __builtin
  __helpers
  addTopLevelDecl
  builtin_typedef_map
  createHelperCallNode
  eql
  failDecl
  failDeclExtra
  getFnProto
  getMangle
  hash
  locStr
  translate
}

compiler.util {
  aroDiagnosticsToErrorBundle
}

